export type Product = {
  id: string;
  slug: string;
  name: string;
  brand: string;
  category: "Phones" | "Laptops" | "Audio" | "Wearables" | "Accessories";
  price: number;
  compareAtPrice?: number;
  currency: string;
  rating: number;
  reviewsCount: number;
  inStock: boolean;
  stockCount: number;
  images: string[];
  shortDescription: string;
  fullDescription: string;
  specs: Record<string, string>;
  tags: string[];
};

export const products: Product[] = [
  // Phones
  {
    id: "1",
    slug: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    category: "Phones",
    price: 1199,
    compareAtPrice: 1299,
    currency: "USD",
    rating: 4.8,
    reviewsCount: 2847,
    inStock: true,
    stockCount: 45,
    images: ["/products/iphone15.svg", "/products/iphone15.svg"],
    shortDescription: "The ultimate iPhone with titanium design and A17 Pro chip",
    fullDescription: "Experience the pinnacle of smartphone innovation with the iPhone 15 Pro Max. Featuring a stunning 6.7-inch Super Retina XDR display, aerospace-grade titanium frame, and the revolutionary A17 Pro chip with 6-core GPU for unmatched performance. Capture professional-quality photos with the advanced 48MP camera system and enjoy all-day battery life.",
    specs: {
      "Display": "6.7-inch Super Retina XDR",
      "Processor": "A17 Pro chip",
      "Camera": "48MP Main + 12MP Ultra Wide + 12MP Telephoto",
      "Storage": "256GB",
      "Battery": "Up to 29 hours video playback",
      "5G": "Yes",
      "Water Resistance": "IP68"
    },
    tags: ["flagship", "5G", "pro camera", "trending"]
  },
  {
    id: "2",
    slug: "samsung-galaxy-s24-ultra",
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    category: "Phones",
    price: 1299,
    compareAtPrice: 1399,
    currency: "USD",
    rating: 4.7,
    reviewsCount: 1923,
    inStock: true,
    stockCount: 32,
    images: ["/products/galaxy-s24.svg", "/products/galaxy-s24.svg"],
    shortDescription: "Premium Android flagship with S Pen and 200MP camera",
    fullDescription: "The Galaxy S24 Ultra redefines mobile excellence with its 6.8-inch Dynamic AMOLED display, Snapdragon 8 Gen 3 processor, and revolutionary 200MP camera. Built-in S Pen provides precision control, while AI-enhanced photography captures stunning details in any light. Premium titanium frame ensures durability and style.",
    specs: {
      "Display": "6.8-inch Dynamic AMOLED 2X",
      "Processor": "Snapdragon 8 Gen 3",
      "Camera": "200MP Main + 12MP Ultra Wide + 50MP Periscope + 10MP Telephoto",
      "Storage": "512GB",
      "RAM": "12GB",
      "Battery": "5000mAh",
      "S Pen": "Included"
    },
    tags: ["flagship", "s-pen", "200mp camera", "trending"]
  },
  {
    id: "3",
    slug: "google-pixel-8-pro",
    name: "Google Pixel 8 Pro",
    brand: "Google",
    category: "Phones",
    price: 999,
    currency: "USD",
    rating: 4.6,
    reviewsCount: 1456,
    inStock: true,
    stockCount: 28,
    images: ["/products/iphone15.svg", "/products/iphone15.svg"],
    shortDescription: "AI-powered photography and pure Android experience",
    fullDescription: "The Pixel 8 Pro brings Google's AI prowess to your pocket. Powered by the custom-designed Tensor G3 chip, enjoy unmatched computational photography, real-time language translation, and the purest Android experience with 7 years of updates guaranteed.",
    specs: {
      "Display": "6.7-inch LTPO OLED",
      "Processor": "Google Tensor G3",
      "Camera": "50MP Main + 48MP Ultra Wide + 48MP Telephoto",
      "Storage": "256GB",
      "RAM": "12GB",
      "Battery": "5050mAh",
      "Updates": "7 years guaranteed"
    },
    tags: ["ai-camera", "pure android", "long updates"]
  },
  {
    id: "4",
    slug: "oneplus-12",
    name: "OnePlus 12",
    brand: "OnePlus",
    category: "Phones",
    price: 799,
    compareAtPrice: 899,
    currency: "USD",
    rating: 4.5,
    reviewsCount: 987,
    inStock: true,
    stockCount: 52,
    images: ["/products/galaxy-s24.svg", "/products/galaxy-s24.svg"],
    shortDescription: "Flagship performance at an incredible value",
    fullDescription: "OnePlus 12 delivers flagship features without the flagship price. Snapdragon 8 Gen 3, stunning AMOLED display with 120Hz, and lightning-fast 100W charging. Hasselblad-tuned cameras produce professional-quality photos.",
    specs: {
      "Display": "6.82-inch AMOLED",
      "Processor": "Snapdragon 8 Gen 3",
      "Camera": "50MP Main + 48MP Ultra Wide + 64MP Telephoto",
      "Storage": "256GB",
      "RAM": "16GB",
      "Battery": "5400mAh",
      "Fast Charging": "100W SuperVOOC"
    },
    tags: ["value", "fast charging", "flagship killer"]
  },

  // Laptops
  {
    id: "5",
    slug: "macbook-pro-16-m3-max",
    name: "MacBook Pro 16\" M3 Max",
    brand: "Apple",
    category: "Laptops",
    price: 3499,
    compareAtPrice: 3699,
    currency: "USD",
    rating: 4.9,
    reviewsCount: 1234,
    inStock: true,
    stockCount: 18,
    images: ["/products/dell-laptop.svg", "/products/dell-laptop.svg"],
    shortDescription: "Ultimate pro laptop with M3 Max chip and Liquid Retina XDR",
    fullDescription: "The MacBook Pro 16-inch with M3 Max chip is the most powerful laptop ever created. Featuring up to 128GB unified memory, stunning Liquid Retina XDR display, and up to 22 hours of battery life. Perfect for video editing, 3D rendering, and professional creative work.",
    specs: {
      "Display": "16.2-inch Liquid Retina XDR",
      "Processor": "Apple M3 Max chip",
      "GPU": "40-core",
      "Memory": "48GB unified memory",
      "Storage": "1TB SSD",
      "Battery": "Up to 22 hours",
      "Ports": "3x Thunderbolt 4, HDMI, SD card, MagSafe 3"
    },
    tags: ["pro", "creative", "m3 max", "trending"]
  },
  {
    id: "6",
    slug: "dell-xps-15-oled",
    name: "Dell XPS 15 OLED",
    brand: "Dell",
    category: "Laptops",
    price: 1999,
    compareAtPrice: 2199,
    currency: "USD",
    rating: 4.6,
    reviewsCount: 876,
    inStock: true,
    stockCount: 24,
    images: ["/products/dell-laptop.svg", "/products/dell-laptop.svg"],
    shortDescription: "Stunning OLED display meets powerful performance",
    fullDescription: "The XPS 15 combines a breathtaking 15.6-inch OLED touchscreen with Intel's latest processors and NVIDIA RTX graphics. Premium build quality, excellent keyboard, and long battery life make it perfect for professionals and creators.",
    specs: {
      "Display": "15.6-inch OLED 3.5K touchscreen",
      "Processor": "Intel Core i7-13700H",
      "GPU": "NVIDIA RTX 4050",
      "Memory": "32GB DDR5",
      "Storage": "1TB PCIe SSD",
      "Battery": "Up to 13 hours",
      "Weight": "4.23 lbs"
    },
    tags: ["oled", "creator laptop", "touchscreen"]
  },
  {
    id: "7",
    slug: "lenovo-thinkpad-x1-carbon-gen-11",
    name: "Lenovo ThinkPad X1 Carbon Gen 11",
    brand: "Lenovo",
    category: "Laptops",
    price: 1799,
    currency: "USD",
    rating: 4.7,
    reviewsCount: 654,
    inStock: true,
    stockCount: 35,
    images: ["/products/hp-desktop.svg", "/products/hp-desktop.svg"],
    shortDescription: "Legendary business ultrabook with military-grade durability",
    fullDescription: "The ThinkPad X1 Carbon continues its legacy as the ultimate business laptop. Featuring carbon fiber construction, legendary keyboard, enterprise-level security, and all-day battery life. Weighing just 2.48 lbs, it's perfect for mobile professionals.",
    specs: {
      "Display": "14-inch 2.8K OLED",
      "Processor": "Intel Core i7-1365U",
      "Memory": "32GB LPDDR5",
      "Storage": "1TB PCIe SSD",
      "Battery": "Up to 15 hours",
      "Weight": "2.48 lbs",
      "Security": "TPM 2.0, fingerprint reader"
    },
    tags: ["business", "ultralight", "durable"]
  },
  {
    id: "8",
    slug: "asus-rog-zephyrus-g16",
    name: "ASUS ROG Zephyrus G16",
    brand: "ASUS",
    category: "Laptops",
    price: 2499,
    currency: "USD",
    rating: 4.8,
    reviewsCount: 542,
    inStock: true,
    stockCount: 19,
    images: ["/products/dell-laptop.svg", "/products/dell-laptop.svg"],
    shortDescription: "Gaming powerhouse with RTX 4080 and Mini LED display",
    fullDescription: "Experience gaming perfection with the ROG Zephyrus G16. Powered by Intel Core i9 and NVIDIA RTX 4080, this slim gaming laptop features a stunning Mini LED display with 240Hz refresh rate. Advanced cooling keeps performance at peak levels.",
    specs: {
      "Display": "16-inch Mini LED 2.5K 240Hz",
      "Processor": "Intel Core i9-13900H",
      "GPU": "NVIDIA RTX 4080",
      "Memory": "32GB DDR5",
      "Storage": "2TB PCIe 4.0 SSD",
      "Cooling": "ROG Intelligent Cooling",
      "RGB": "Per-key RGB keyboard"
    },
    tags: ["gaming", "high-performance", "mini-led"]
  },
  {
    id: "9",
    slug: "microsoft-surface-laptop-5",
    name: "Microsoft Surface Laptop 5",
    brand: "Microsoft",
    category: "Laptops",
    price: 1299,
    compareAtPrice: 1499,
    currency: "USD",
    rating: 4.5,
    reviewsCount: 734,
    inStock: true,
    stockCount: 41,
    images: ["/products/hp-desktop.svg", "/products/hp-desktop.svg"],
    shortDescription: "Elegant design meets Windows 11 perfection",
    fullDescription: "The Surface Laptop 5 combines premium design with powerful performance. Featuring a vibrant PixelSense touchscreen, Alcantara keyboard, and all-day battery life. Perfect integration with Windows 11 and Microsoft ecosystem.",
    specs: {
      "Display": "13.5-inch PixelSense touchscreen",
      "Processor": "Intel Core i7-1255U",
      "Memory": "16GB LPDDR5x",
      "Storage": "512GB SSD",
      "Battery": "Up to 18 hours",
      "Weight": "2.86 lbs",
      "Material": "Alcantara keyboard deck"
    },
    tags: ["elegant", "touchscreen", "windows"]
  },
  {
    id: "10",
    slug: "hp-spectre-x360-14",
    name: "HP Spectre x360 14",
    brand: "HP",
    category: "Laptops",
    price: 1599,
    currency: "USD",
    rating: 4.6,
    reviewsCount: 489,
    inStock: true,
    stockCount: 27,
    images: ["/products/hp-desktop.svg", "/products/hp-desktop.svg"],
    shortDescription: "Premium 2-in-1 convertible with gem-cut design",
    fullDescription: "The Spectre x360 14 is a stunning 2-in-1 that transforms from laptop to tablet effortlessly. OLED display delivers vibrant colors, while the gem-cut design and premium materials make a statement. Includes HP rechargeable pen.",
    specs: {
      "Display": "13.5-inch 3K2K OLED touchscreen",
      "Processor": "Intel Core i7-1355U",
      "Memory": "16GB LPDDR4x",
      "Storage": "1TB PCIe SSD",
      "Battery": "Up to 13 hours",
      "Convertible": "360-degree hinge",
      "Pen": "HP Rechargeable Pen included"
    },
    tags: ["2-in-1", "oled", "convertible"]
  },

  // Audio
  {
    id: "11",
    slug: "sony-wh-1000xm5",
    name: "Sony WH-1000XM5",
    brand: "Sony",
    category: "Audio",
    price: 399,
    compareAtPrice: 449,
    currency: "USD",
    rating: 4.8,
    reviewsCount: 3421,
    inStock: true,
    stockCount: 67,
    images: ["/products/headphones.svg", "/products/headphones.svg"],
    shortDescription: "Industry-leading noise cancellation and premium sound",
    fullDescription: "The WH-1000XM5 sets the gold standard for wireless headphones. Featuring revolutionary noise cancellation, exceptional 30-hour battery life, and premium sound quality. Multiple microphones ensure crystal-clear calls, while intuitive touch controls make operation effortless.",
    specs: {
      "Driver": "30mm carbon fiber",
      "Noise Cancellation": "Industry-leading ANC",
      "Battery": "Up to 30 hours",
      "Fast Charge": "3 hours from 3 minutes",
      "Bluetooth": "5.2 with multipoint",
      "Weight": "250g",
      "Codecs": "LDAC, AAC, SBC"
    },
    tags: ["noise-cancelling", "premium audio", "trending", "bestseller"]
  },
  {
    id: "12",
    slug: "apple-airpods-pro-2",
    name: "AirPods Pro (2nd Gen)",
    brand: "Apple",
    category: "Audio",
    price: 249,
    currency: "USD",
    rating: 4.7,
    reviewsCount: 5678,
    inStock: true,
    stockCount: 94,
    images: ["/products/headphones.svg", "/products/headphones.svg"],
    shortDescription: "Magical audio experience with adaptive noise cancellation",
    fullDescription: "AirPods Pro deliver an immersive listening experience with adaptive audio that automatically adjusts to your environment. H2 chip enables smarter noise cancellation and spatial audio with dynamic head tracking. MagSafe charging case provides multiple charges.",
    specs: {
      "Chip": "Apple H2",
      "Noise Cancellation": "Adaptive ANC",
      "Battery": "6 hours (30 with case)",
      "Spatial Audio": "Yes with head tracking",
      "Water Resistance": "IPX4",
      "Charging": "MagSafe, Qi wireless, Lightning",
      "Controls": "Touch control + volume slider"
    },
    tags: ["apple ecosystem", "spatial audio", "bestseller"]
  },
  {
    id: "13",
    slug: "bose-quietcomfort-ultra",
    name: "Bose QuietComfort Ultra",
    brand: "Bose",
    category: "Audio",
    price: 429,
    currency: "USD",
    rating: 4.7,
    reviewsCount: 1234,
    inStock: true,
    stockCount: 38,
    images: ["/products/headphones.svg", "/products/headphones.svg"],
    shortDescription: "Legendary comfort meets immersive spatial audio",
    fullDescription: "QuietComfort Ultra delivers the comfort Bose is famous for with cutting-edge spatial audio. CustomTune technology personalizes sound to your ears, while world-class noise cancellation eliminates distractions. Premium materials ensure all-day comfort.",
    specs: {
      "Driver": "Proprietary Bose TriPort",
      "Spatial Audio": "Immersive Audio",
      "Battery": "24 hours",
      "Noise Cancellation": "World-class ANC",
      "Bluetooth": "5.3",
      "Weight": "254g",
      "Codecs": "aptX Adaptive, AAC"
    },
    tags: ["comfort", "spatial audio", "premium"]
  },
  {
    id: "14",
    slug: "sennheiser-momentum-4",
    name: "Sennheiser Momentum 4",
    brand: "Sennheiser",
    category: "Audio",
    price: 379,
    compareAtPrice: 429,
    currency: "USD",
    rating: 4.6,
    reviewsCount: 876,
    inStock: true,
    stockCount: 29,
    images: ["/products/headphones.svg", "/products/headphones.svg"],
    shortDescription: "Audiophile-grade sound with marathon battery life",
    fullDescription: "Momentum 4 delivers Sennheiser's legendary sound quality with modern features. Exceptional 60-hour battery life means weeks between charges. Adaptive noise cancellation and transparent hearing keep you connected to your surroundings when needed.",
    specs: {
      "Driver": "42mm transducer",
      "Battery": "Up to 60 hours",
      "Noise Cancellation": "Adaptive ANC",
      "Bluetooth": "5.2 with multipoint",
      "Codecs": "aptX Adaptive, AAC, SBC",
      "Weight": "293g",
      "Sound Personalization": "Yes via app"
    },
    tags: ["audiophile", "long battery", "premium sound"]
  },
  {
    id: "15",
    slug: "beats-studio-pro",
    name: "Beats Studio Pro",
    brand: "Beats",
    category: "Audio",
    price: 349,
    currency: "USD",
    rating: 4.5,
    reviewsCount: 1567,
    inStock: true,
    stockCount: 56,
    images: ["/products/headphones.svg", "/products/headphones.svg"],
    shortDescription: "Premium sound with lossless audio support",
    fullDescription: "Studio Pro brings professional studio sound quality to everyday listening. Custom acoustic platform delivers rich, immersive audio. Lossless audio support via USB-C ensures perfect fidelity. Seamlessly switch between Apple and Android devices.",
    specs: {
      "Driver": "Custom 40mm",
      "Battery": "Up to 40 hours",
      "Lossless Audio": "Yes via USB-C",
      "Noise Cancellation": "Active ANC",
      "Spatial Audio": "Yes with head tracking",
      "Bluetooth": "5.3 with multipoint",
      "Fast Charge": "10 min = 4 hours"
    },
    tags: ["lossless", "studio sound", "versatile"]
  },
  {
    id: "16",
    slug: "jabra-elite-10",
    name: "Jabra Elite 10",
    brand: "Jabra",
    category: "Audio",
    price: 279,
    currency: "USD",
    rating: 4.6,
    reviewsCount: 723,
    inStock: true,
    stockCount: 48,
    images: ["/products/headphones.svg", "/products/headphones.svg"],
    shortDescription: "Premium earbuds with spatial sound and superior calls",
    fullDescription: "Elite 10 earbuds combine Dolby Atmos spatial sound with advanced noise cancellation. Revolutionary EarGel design ensures perfect fit and comfort for all-day wear. Six-microphone technology delivers crystal-clear calls in any environment.",
    specs: {
      "Driver": "10mm",
      "Spatial Audio": "Dolby Atmos",
      "Battery": "6 hours (27 with case)",
      "Noise Cancellation": "Advanced ANC",
      "Water Resistance": "IP57",
      "Microphones": "6-mic system",
      "Wireless Charging": "Qi compatible"
    },
    tags: ["earbuds", "spatial audio", "great calls"]
  },

  // Wearables
  {
    id: "17",
    slug: "apple-watch-series-9",
    name: "Apple Watch Series 9",
    brand: "Apple",
    category: "Wearables",
    price: 429,
    compareAtPrice: 479,
    currency: "USD",
    rating: 4.8,
    reviewsCount: 4123,
    inStock: true,
    stockCount: 73,
    images: ["/products/headphones.svg", "/products/headphones.svg"],
    shortDescription: "Most advanced health and fitness companion",
    fullDescription: "Series 9 introduces the powerful S9 SiP with double-tap gesture control. Brighter display, advanced health sensors, and comprehensive fitness tracking. Carbon neutral options available. Seamlessly integrates with iPhone and Apple ecosystem.",
    specs: {
      "Display": "Always-On Retina OLED",
      "Chip": "S9 SiP",
      "Health Sensors": "ECG, Blood Oxygen, Temperature",
      "Fitness": "GPS, heart rate, workout modes",
      "Battery": "Up to 18 hours",
      "Water Resistance": "50m",
      "Storage": "64GB"
    },
    tags: ["smartwatch", "health tracking", "apple ecosystem", "trending"]
  },
  {
    id: "18",
    slug: "samsung-galaxy-watch-6-classic",
    name: "Samsung Galaxy Watch 6 Classic",
    brand: "Samsung",
    category: "Wearables",
    price: 399,
    currency: "USD",
    rating: 4.7,
    reviewsCount: 1876,
    inStock: true,
    stockCount: 45,
    images: ["/products/headphones.svg", "/products/headphones.svg"],
    shortDescription: "Premium smartwatch with rotating bezel and comprehensive health",
    fullDescription: "Galaxy Watch 6 Classic brings back the beloved rotating bezel with advanced health monitoring. Track sleep quality, body composition, and more. Sapphire crystal display ensures durability. Works beautifully with Android devices.",
    specs: {
      "Display": "1.5-inch Super AMOLED",
      "Processor": "Exynos W930",
      "Health Sensors": "BioActive sensor, ECG, sleep tracking",
      "Fitness": "90+ workout modes",
      "Battery": "Up to 40 hours",
      "Water Resistance": "5ATM + IP68",
      "Storage": "16GB"
    },
    tags: ["smartwatch", "rotating bezel", "android"]
  },
  {
    id: "19",
    slug: "garmin-fenix-7x-pro",
    name: "Garmin Fenix 7X Pro Solar",
    brand: "Garmin",
    category: "Wearables",
    price: 899,
    currency: "USD",
    rating: 4.8,
    reviewsCount: 892,
    inStock: true,
    stockCount: 22,
    images: ["/products/headphones.svg", "/products/headphones.svg"],
    shortDescription: "Ultimate multisport GPS watch with solar charging",
    fullDescription: "Fenix 7X Pro is the ultimate adventure companion. Solar charging extends battery life to weeks. Comprehensive mapping, advanced training metrics, and multi-band GPS ensure precision. Built for the toughest conditions with military-grade durability.",
    specs: {
      "Display": "1.4-inch solar-powered",
      "GPS": "Multi-band GNSS",
      "Battery": "Up to 28 days (solar)",
      "Sensors": "Heart rate, Pulse Ox, altimeter, compass",
      "Maps": "TopoActive maps",
      "Water Rating": "10ATM",
      "Build": "Sapphire lens, titanium bezel"
    },
    tags: ["outdoor", "gps watch", "solar", "rugged"]
  },
  {
    id: "20",
    slug: "fitbit-charge-6",
    name: "Fitbit Charge 6",
    brand: "Fitbit",
    category: "Wearables",
    price: 159,
    compareAtPrice: 179,
    currency: "USD",
    rating: 4.5,
    reviewsCount: 2341,
    inStock: true,
    stockCount: 87,
    images: ["/products/headphones.svg", "/products/headphones.svg"],
    shortDescription: "Advanced fitness tracker with Google integration",
    fullDescription: "Charge 6 delivers comprehensive health and fitness tracking in a sleek package. Built-in GPS, heart rate monitoring, and stress management tools. Now with Google apps including Maps and Wallet. 7-day battery life keeps you tracking longer.",
    specs: {
      "Display": "Color AMOLED",
      "GPS": "Built-in",
      "Battery": "Up to 7 days",
      "Health": "Heart rate, SpO2, stress, sleep",
      "Fitness": "40+ exercise modes",
      "Water Resistance": "50m",
      "Integration": "Google Maps, Wallet, YouTube Music"
    },
    tags: ["fitness tracker", "affordable", "google integration"]
  },

  // Accessories
  {
    id: "21",
    slug: "logitech-mx-master-3s",
    name: "Logitech MX Master 3S",
    brand: "Logitech",
    category: "Accessories",
    price: 99,
    currency: "USD",
    rating: 4.8,
    reviewsCount: 5432,
    inStock: true,
    stockCount: 124,
    images: ["/products/logitech-mouse.svg", "/products/logitech-mouse.svg"],
    shortDescription: "Ultimate wireless mouse for productivity",
    fullDescription: "MX Master 3S is the ultimate tool for professionals. Featuring quieter clicks, 8K DPI precision, and customizable buttons. MagSpeed electromagnetic scrolling enables lightning-fast navigation. Works seamlessly across up to 3 devices.",
    specs: {
      "DPI": "8000",
      "Buttons": "7 customizable",
      "Battery": "Up to 70 days",
      "Connectivity": "Bluetooth or USB receiver",
      "Multi-device": "Up to 3 devices",
      "Scroll": "MagSpeed electromagnetic",
      "Silent": "90% quieter clicks"
    },
    tags: ["productivity", "wireless mouse", "bestseller", "ergonomic"]
  },
  {
    id: "22",
    slug: "keychron-q1-pro",
    name: "Keychron Q1 Pro",
    brand: "Keychron",
    category: "Accessories",
    price: 199,
    currency: "USD",
    rating: 4.7,
    reviewsCount: 1234,
    inStock: true,
    stockCount: 36,
    images: ["/products/keyboard.svg", "/products/keyboard.svg"],
    shortDescription: "Premium wireless mechanical keyboard with QMK/VIA",
    fullDescription: "Q1 Pro combines premium build quality with wireless freedom. CNC aluminum body, hot-swappable switches, and full customization via QMK/VIA. Tri-mode connectivity includes Bluetooth multipoint. Perfect for enthusiasts and professionals alike.",
    specs: {
      "Layout": "75% compact",
      "Switches": "Hot-swappable (Gateron Pro)",
      "Keycaps": "Double-shot PBT",
      "Build": "CNC aluminum case",
      "Connectivity": "Bluetooth, 2.4GHz, USB-C",
      "Battery": "4000mAh (up to 300 hours)",
      "Customization": "QMK/VIA support"
    },
    tags: ["mechanical keyboard", "wireless", "customizable", "premium"]
  },
  {
    id: "23",
    slug: "anker-prime-power-bank",
    name: "Anker Prime 27,650mAh Power Bank",
    brand: "Anker",
    category: "Accessories",
    price: 179,
    compareAtPrice: 199,
    currency: "USD",
    rating: 4.7,
    reviewsCount: 876,
    inStock: true,
    stockCount: 58,
    images: ["/products/logitech-mouse.svg", "/products/logitech-mouse.svg"],
    shortDescription: "Massive capacity with 140W fast charging",
    fullDescription: "The Anker Prime power bank provides enough power to charge laptops, tablets, and phones multiple times. 140W USB-C PD output charges MacBook Pro to 50% in just 30 minutes. Smart display shows real-time charging information. Perfect for travel and emergencies.",
    specs: {
      "Capacity": "27,650mAh (99.54Wh)",
      "Output": "140W USB-C PD 3.1",
      "Ports": "2x USB-C, 1x USB-A",
      "Input": "140W recharge in 46 minutes",
      "Display": "Smart digital display",
      "Compatibility": "Laptops, phones, tablets",
      "Safety": "MultiProtect system"
    },
    tags: ["power bank", "fast charging", "high capacity", "travel"]
  },
  {
    id: "24",
    slug: "belkin-3in1-magsafe-charger",
    name: "Belkin 3-in-1 MagSafe Charger",
    brand: "Belkin",
    category: "Accessories",
    price: 149,
    currency: "USD",
    rating: 4.6,
    reviewsCount: 1543,
    inStock: true,
    stockCount: 67,
    images: ["/products/logitech-mouse.svg", "/products/logitech-mouse.svg"],
    shortDescription: "Charge iPhone, Apple Watch, and AirPods simultaneously",
    fullDescription: "This elegant charging stand charges all your Apple devices at once. Official MagSafe charging for iPhone up to 15W, Apple Watch fast charging, and AirPods wireless charging pad. Minimalist design complements any desk or nightstand.",
    specs: {
      "iPhone Charging": "15W MagSafe",
      "Apple Watch": "Fast charging compatible",
      "AirPods": "5W Qi wireless",
      "Design": "Weighted steel base",
      "Cable": "2m braided USB-C",
      "Certification": "Apple MFi certified",
      "Compatibility": "iPhone 12 and later"
    },
    tags: ["magsafe", "3-in-1", "apple ecosystem", "premium"]
  }
];
